# Generated by Django 5.2 on 2025-07-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_options_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
