# Generated by Django 5.2 on 2025-07-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
