# Generated by Django 5.2 on 2025-07-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='reason',
            field=models.CharField(choices=[('venda', 'Venda'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste de estoque'), ('outro', 'Outro')], default='venda', max_length=20),
        ),
    ]
