# Generated by Django 5.2 on 2025-07-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_outflow_reason'),
        ('products', '0005_alter_product_options_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída', 'verbose_name_plural': 'Saídas'},
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='reason',
            field=models.CharField(choices=[('venda', 'Venda'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste de estoque'), ('outro', 'Outro')], default='venda', max_length=20, verbose_name='Motivo'),
        ),
    ]
