# Generated by Django 5.2 on 2025-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_inflow_invoice_number_inflow_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
