# Generated by Django 5.2 on 2025-07-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0004_alter_inflow_invoice_number'),
        ('products', '0005_alter_product_options_alter_product_brand_and_more'),
        ('suppliers', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterField(
            model_name='inflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Compra'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inflows', to='suppliers.supplier', verbose_name='Fornecedor'),
        ),
    ]
