# Generated by Django 5.2 on 2025-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
