# Generated by Django 5.2 on 2025-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_internal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='serie_number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
