# Generated by Django 5.2 on 2025-07-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_internal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serie_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
